// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-saas/kit/pkg/api"
	"github.com/go-saas/kit/pkg/authn/jwt"
	"github.com/go-saas/kit/pkg/authz/authz"
	"github.com/go-saas/kit/pkg/conf"
	api2 "github.com/go-saas/kit/saas/api"
	api3 "github.com/go-saas/kit/user/api"
	"github.com/go-saas/saas/http"
)

import (
	_ "github.com/go-saas/kit/gateway/apisix/cmd/go-runner/plugins"
	_ "github.com/go-saas/kit/pkg/registry/etcd"
)

// Injectors from wire.go:

func initApp(services *conf.Services, security *conf.Security, webMultiTenancyOption *http.WebMultiTenancyOption, clientName api.ClientName, logger log.Logger, arg ...grpc.ClientOption) (*App, func(), error) {
	client := api.NewClientCfg(clientName, services)
	discovery, err := api.NewDiscovery(services)
	if err != nil {
		return nil, nil, err
	}
	option := NewSelfClientOption(logger)
	tokenizerConfig := jwt.NewTokenizerConfig(security)
	tokenizer := jwt.NewTokenizer(tokenizerConfig)
	inMemoryTokenManager := api.NewInMemoryTokenManager(tokenizer, logger)
	grpcConn, cleanup := api2.NewGrpcConn(client, services, discovery, option, inMemoryTokenManager, logger, arg...)
	tenantInternalServiceServer := api2.NewTenantInternalGrpcClient(grpcConn)
	tenantStore := api2.NewTenantStore(tenantInternalServiceServer)
	apiGrpcConn, cleanup2 := api3.NewGrpcConn(client, services, discovery, option, inMemoryTokenManager, logger, arg...)
	userServiceServer := api3.NewUserGrpcClient(apiGrpcConn)
	userTenantContrib := api3.NewUserTenantContrib(userServiceServer)
	authServer := api3.NewAuthGrpcClient(apiGrpcConn)
	refreshTokenProvider := api3.NewRefreshProvider(authServer, logger)
	permissionServiceServer := api3.NewPermissionGrpcClient(apiGrpcConn)
	permissionChecker := api3.NewRemotePermissionChecker(permissionServiceServer)
	authzOption := NewAuthorizationOption()
	subjectResolverImpl := authz.NewSubjectResolver(authzOption)
	defaultAuthorizationService := authz.NewDefaultAuthorizationService(permissionChecker, subjectResolverImpl, logger)
	app, err := newApp(tenantStore, userTenantContrib, tokenizer, inMemoryTokenManager, services, clientName, webMultiTenancyOption, security, refreshTokenProvider, defaultAuthorizationService, subjectResolverImpl, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
