/* tslint:disable */
/* eslint-disable */
/**
 * Saas Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DataAddress
 */
export interface DataAddress {
  /**
   *
   * @type {string}
   * @memberof DataAddress
   */
  country?: string;
  /**
   *
   * @type {string}
   * @memberof DataAddress
   */
  state?: string;
  /**
   *
   * @type {string}
   * @memberof DataAddress
   */
  city?: string;
  /**
   *
   * @type {string}
   * @memberof DataAddress
   */
  zipCode?: string;
  /**
   *
   * @type {string}
   * @memberof DataAddress
   */
  line1?: string;
  /**
   *
   * @type {string}
   * @memberof DataAddress
   */
  line2?: string;
  /**
   *
   * @type {string}
   * @memberof DataAddress
   */
  line3?: string;
  /**
   *
   * @type {string}
   * @memberof DataAddress
   */
  longitude?: string;
  /**
   *
   * @type {string}
   * @memberof DataAddress
   */
  latitude?: string;
}
