/* tslint:disable */
/* eslint-disable */
/**
 * Saas Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1UserRole } from './v1-user-role';

/**
 *
 * @export
 * @interface V1GetUserRoleReply
 */
export interface V1GetUserRoleReply {
  /**
   *
   * @type {Array<V1UserRole>}
   * @memberof V1GetUserRoleReply
   */
  roles?: Array<V1UserRole>;
}
