// Code generated by protoc-gen-go-grpc-proxy. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc-proxy v1.2.0
// - protoc             (unknown)
// source: user/api/account/v1/account.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

var _ AccountServer = (*accountClientProxy)(nil)

// accountClientProxy is the proxy to turn Account client to server interface.
type accountClientProxy struct {
	cc AccountClient
}

func NewAccountClientProxy(cc AccountClient) AccountServer {
	return &accountClientProxy{cc}
}

func (c *accountClientProxy) GetProfile(ctx context.Context, in *GetProfileRequest) (*GetProfileResponse, error) {
	return c.cc.GetProfile(ctx, in)
}
func (c *accountClientProxy) UpdateProfile(ctx context.Context, in *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return c.cc.UpdateProfile(ctx, in)
}
func (c *accountClientProxy) GetSettings(ctx context.Context, in *GetSettingsRequest) (*GetSettingsResponse, error) {
	return c.cc.GetSettings(ctx, in)
}
func (c *accountClientProxy) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest) (*UpdateSettingsResponse, error) {
	return c.cc.UpdateSettings(ctx, in)
}
func (c *accountClientProxy) GetAddresses(ctx context.Context, in *GetAddressesRequest) (*GetAddressesReply, error) {
	return c.cc.GetAddresses(ctx, in)
}
func (c *accountClientProxy) CreateAddresses(ctx context.Context, in *CreateAddressesRequest) (*CreateAddressReply, error) {
	return c.cc.CreateAddresses(ctx, in)
}
func (c *accountClientProxy) UpdateAddresses(ctx context.Context, in *UpdateAddressesRequest) (*UpdateAddressesReply, error) {
	return c.cc.UpdateAddresses(ctx, in)
}
func (c *accountClientProxy) DeleteAddresses(ctx context.Context, in *DeleteAddressRequest) (*DeleteAddressesReply, error) {
	return c.cc.DeleteAddresses(ctx, in)
}
