/* tslint:disable */
/* eslint-disable */
/**
 * Saas Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1OAuthProvider } from './v1-oauth-provider';

/**
 *
 * @export
 * @interface V1GetLoginResponse
 */
export interface V1GetLoginResponse {
  /**
   *
   * @type {string}
   * @memberof V1GetLoginResponse
   */
  redirect?: string;
  /**
   *
   * @type {Array<V1OAuthProvider>}
   * @memberof V1GetLoginResponse
   */
  oauth?: Array<V1OAuthProvider>;
  /**
   *
   * @type {string}
   * @memberof V1GetLoginResponse
   */
  hint?: string;
  /**
   *
   * @type {string}
   * @memberof V1GetLoginResponse
   */
  challenge?: string;
}
