/* tslint:disable */
/* eslint-disable */
/**
 * Saas Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */

export const V1PermissionSide = {
  Both: 'BOTH',
  HostOnly: 'HOST_ONLY',
  TenantOnly: 'TENANT_ONLY',
} as const;

export type V1PermissionSide = typeof V1PermissionSide[keyof typeof V1PermissionSide];
