// Code generated by protoc-gen-go-grpc-proxy. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc-proxy v1.2.0
// - protoc             (unknown)
// source: oidc/api/client/v1/client.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

var _ ClientServiceServer = (*clientServiceClientProxy)(nil)

// clientServiceClientProxy is the proxy to turn ClientService client to server interface.
type clientServiceClientProxy struct {
	cc ClientServiceClient
}

func NewClientServiceClientProxy(cc ClientServiceClient) ClientServiceServer {
	return &clientServiceClientProxy{cc}
}

func (c *clientServiceClientProxy) ListOAuth2Clients(ctx context.Context, in *ListClientRequest) (*OAuth2ClientList, error) {
	return c.cc.ListOAuth2Clients(ctx, in)
}
func (c *clientServiceClientProxy) GetOAuth2Client(ctx context.Context, in *GetOAuth2ClientRequest) (*OAuth2Client, error) {
	return c.cc.GetOAuth2Client(ctx, in)
}
func (c *clientServiceClientProxy) CreateOAuth2Client(ctx context.Context, in *OAuth2Client) (*OAuth2Client, error) {
	return c.cc.CreateOAuth2Client(ctx, in)
}
func (c *clientServiceClientProxy) DeleteOAuth2Client(ctx context.Context, in *DeleteOAuth2ClientRequest) (*emptypb.Empty, error) {
	return c.cc.DeleteOAuth2Client(ctx, in)
}
func (c *clientServiceClientProxy) PatchOAuth2Client(ctx context.Context, in *PatchOAuth2ClientRequest) (*OAuth2Client, error) {
	return c.cc.PatchOAuth2Client(ctx, in)
}
func (c *clientServiceClientProxy) UpdateOAuth2Client(ctx context.Context, in *UpdateOAuth2ClientRequest) (*OAuth2Client, error) {
	return c.cc.UpdateOAuth2Client(ctx, in)
}
